name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWD: ${{secrets.DOCKER_PASSWD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-django-app:$(date +%s)
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/test-django-app:v1.0

